algoritmo "Exemplo Vetor"

var
   nome_alunos:vetor[1..5] de literal
inicio
   nome_alunos[1] <- "Vinicim"
   nome_alunos[2] <- "Alexandre"
   nome_alunos[3] <- "Geovani"
   nome_alunos[4] <- "Gabriel"
   nome_alunos[5] <- "Hiago"
   
   escreval("O nome é: ", nome_alunos[1])
   escreval("O nome é: ", nome_alunos[2])
   escreval("O nome é: ", nome_alunos[3])
   escreval("O nome é: ", nome_alunos[4])
   escreval("O nome é: ", nome_alunos[5])


fimalgoritmo
